### ISSUE TITLE
search not working on readthedocs

### ISSUE THREAD

**Issue by jfkcooper** [refnx/refnx#658] opened 2023-03-10 14:43 UTC
I'm not sure why this even possibly could be, but the current readthedocs page for refnx doesn't search for me (two different devices), I just get a "searching..." page but never any results. It has been this way for a few days at least.

**Comment by andyfaff** [comment] 2023-03-11 07:33
Thanks for reporting. I don't know why that is. I was going to suggest looking at the version switcher and see if an old version of search worked, but the switcher doesn't work either.

https://refnx.readthedocs.io/en/stable seems to work, just not latest.

Sphinx/RST is not my forte. I'm guessing one of the sphinx themes is broken

**Comment by andyfaff** [comment] 2023-03-11 08:48
Now fixed, thanks @jfkcooper. I think it was caused by https://github.com/readthedocs/readthedocs.org/pull/9654

**Closed by andyfaff** 2023-03-11 08:48 UTC
